### ISSUE TITLE
ZipException: error in opening zip file

### ISSUE THREAD

**Issue by johnjohndoe** [bjoernQ/unmock-plugin#30]
I am using version 0.6.0 in a multi-module Android project as described in #23. 
In most cased builds run without problems but **randomly** the **build fails** with a `ZipException`:

``` java
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':commons:unMock'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)

Caused by: java.util.zip.ZipException: error in opening zip file
	at de.mobilej.ProcessRealAndroidJar.findAllClazzesIn(ProcessRealAndroidJar.java:306)
	at de.mobilej.ProcessRealAndroidJar.process(ProcessRealAndroidJar.java:115)
	at de.mobilej.unmock.UnMockPlugin$_apply_closure1$_closure4.doCall(UnMockPlugin.groovy:60)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more
```

Is there anything I can do to provide you with more information to resolve this issue permanently?!

### Related issues

- #23 "Error in opening zip file" when including the plugin twice
- #16 Error : Execution failed for task ':app:unMock'

**Comment by bjoernQ** [comment]
Are you using the "downloadFrom" or the unmock dependency to specify the android-all.jar

Something like this happens usually only with the "downloadFrom" approach. In that case the plugin downloads the JAR on it's own (and it doesn't do a perfect job there). Because of that the unmock-dependency is the much better way because in that case the downloading and caching of the artifact is handled by Gradle's robust mechanisms.

**Comment by johnjohndoe** [comment]
No, I am not using the `downloadFrom` as [explained in the README.md of v.3.3](https://github.com/bjoernQ/unmock-plugin/blob/0.3.3/README.md).

**Comment by bjoernQ** [comment]
Would you mind switching to the dependency? It should really improve the situation. Since you are already on the latest version it should be a small change.

**Comment by johnjohndoe** [comment]
Not sure if I understand you correctly. As written before, I am **not** specifying a custom download URL via `downloadFrom` which you named as a potential source of the issue.
What do you want me to instead? Please post an example configuration.

**Comment by bjoernQ** [comment]
Sorry for the confusion.

Do you have s.th. like this in your build files instead?

```groovy
dependencies {
    // dependency to android-all to use
    unmock 'org.robolectric:android-all:4.3_r2-robolectric-0'
}
```

Because if you omit the _downloadFrom_ it takes a default but that default will use the old way of downloading the JAR unless you specify the unmock dependency.

**Comment by johnjohndoe** [comment]
No, I have not declared this line in any of the _build.gradle_ files.

**Comment by bjoernQ** [comment]
That's good - adding it should make your builds more reliable.

After adding it you can double check it by deleting the downloaded android-all.jar from the temp directory and running the tests clean. If it doesn't appear again all build files use the new way of getting the android-all artifact.

The file in the temp folder is  _https___oss.sonatype.org_content_groups_public_org_robolectric_android-all_4.3_r2-robolectric-0_android-all-4.3_r2-robolectric-0.jar_

**Comment by johnjohndoe** [comment]
Where would I find the _temp_ folder with the _*.jar_? In `/tmp` or in the workspace of the project?

**Comment by bjoernQ** [comment]
It's the system's temp folder. On Linux usually /tmp

Tobias Preuss <notifications@github.com> schrieb am Do., 11. Mai 2017,
16:18:

**Comment by johnjohndoe** [comment]
I just built the project from command line without changing the configuration and the issue appeared. Neither, in the workspace of the project nor in `/tmp` is such a `*.jar` file. I work on MacOS.

**Comment by bjoernQ** [comment]
OSX is a bit special regarding the temp folder.

See https://superuser.com/questions/581347/where-is-the-temp-folder-in-os-x

Hope this helps.

Tobias Preuss <notifications@github.com> schrieb am Do., 11. Mai 2017,
16:41:

**Comment by johnjohndoe** [comment]
Thank you for the hint. I found the `*.jar` in the temp folder.
I deleted it there and ran a fresh build with applying your configuration. I see that Gradle downloads the `*.jar` and after the successful build I found the file in the Gradle cache:

> ~/.gradle/caches/modules-2/files-2.1/org.robolectric/android-all/4.3_r2-robolectric-0

Looks good to me. I think I will try this for a longer run.
I would say you can close the issue for now.
Thank you for the quick support!

**Comment by bjoernQ** [comment]
Nice to hear that. Hopefully this will help.
