### ISSUE TITLE
NullPointerException in ProcessRealAndroidJar

### ISSUE THREAD

**Issue by zawadz88** [bjoernQ/unmock-plugin#63]
Hi,
When building on CI we sometimes see the following error:
```
Execution failed for task ':app:unMock'.
error	06-Apr-2020 10:17:43	> Exception while unmocking
```
I've attached a complete stack trace at the bottom.

**Some more info about our setup:**
Gradle 6.2
Android Gradle Plugin 3.6.0
unmock 0.7.5
We have ~30 Gradle modules, unmock plugin is applied to most of them. We also use flavors for most of the modules.
Unmock task fails for random modules

I'm not sure about this, but I think the issue did not occur before 0.7.5 (we used 0.7.3 and 0.6.4 before). Or at least it did not occur so often.
I can provide more details when needed.

**Stack trace:**
```
* Exception is:
error	06-Apr-2020 10:17:43	org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:unMock'.
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
error	06-Apr-2020 10:17:43		at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
error	06-Apr-2020 10:17:43		at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
error	06-Apr-2020 10:17:43		at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
error	06-Apr-2020 10:17:43		at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
error	06-Apr-2020 10:17:43		at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
error	06-Apr-2020 10:17:43		at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
error	06-Apr-2020 10:17:43		at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
error	06-Apr-2020 10:17:43		at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
error	06-Apr-2020 10:17:43		at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
error	06-Apr-2020 10:17:43		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
error	06-Apr-2020 10:17:43		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
error	06-Apr-2020 10:17:43		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
error	06-Apr-2020 10:17:43		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
error	06-Apr-2020 10:17:43		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
error	06-Apr-2020 10:17:43		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
error	06-Apr-2020 10:17:43		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
error	06-Apr-2020 10:17:43		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
error	06-Apr-2020 10:17:43		at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
error	06-Apr-2020 10:17:43		at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
error	06-Apr-2020 10:17:43		at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
error	06-Apr-2020 10:17:43	Caused by: org.gradle.api.GradleException: Exception while unmocking
error	06-Apr-2020 10:17:43		at de.mobilej.UnMockTask.unmock(UnMockTask.java:134)
error	06-Apr-2020 10:17:43		at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:727)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:568)
error	06-Apr-2020 10:17:43		at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
error	06-Apr-2020 10:17:43		at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
error	06-Apr-2020 10:17:43		at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
error	06-Apr-2020 10:17:43		at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
error	06-Apr-2020 10:17:43		at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
error	06-Apr-2020 10:17:43		at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
error	06-Apr-2020 10:17:43		at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:553)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:536)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:276)
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:265)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:153)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:67)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:41)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
build	06-Apr-2020 10:17:43	
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
build	06-Apr-2020 10:17:43	Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
build	06-Apr-2020 10:17:43	Use '--warning-mode all' to show the individual deprecation warnings.
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
build	06-Apr-2020 10:17:43	See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
error	06-Apr-2020 10:17:43		at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
build	06-Apr-2020 10:17:43	676 actionable tasks: 676 executed
error	06-Apr-2020 10:17:43		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:192)
error	06-Apr-2020 10:17:43		... 30 more
error	06-Apr-2020 10:17:43	Caused by: java.lang.NullPointerException
error	06-Apr-2020 10:17:43		at javassist.JarClassPath.openClassfile(ClassPoolTail.java:163)
error	06-Apr-2020 10:17:43		at javassist.ClassPoolTail.openClassfile(ClassPoolTail.java:340)
error	06-Apr-2020 10:17:43		at javassist.ClassPoolTail.writeClassfile(ClassPoolTail.java:293)
error	06-Apr-2020 10:17:43		at javassist.ClassPool.writeClassfile(ClassPool.java:627)
error	06-Apr-2020 10:17:43		at javassist.CtClassType.toBytecode(CtClassType.java:1589)
error	06-Apr-2020 10:17:43		at javassist.CtClass.writeFile(CtClass.java:1556)
error	06-Apr-2020 10:17:43		at de.mobilej.ProcessRealAndroidJar.process(ProcessRealAndroidJar.java:152)
error	06-Apr-2020 10:17:43		at de.mobilej.UnMockTask.unmock(UnMockTask.java:124)
error	06-Apr-2020 10:17:43		... 92 more
```

This seems to be the line: https://github.com/bjoernQ/unmock-plugin/blob/master/buildSrc/src/main/java/de/mobilej/ProcessRealAndroidJar.java#L152

**Comment by bjoernQ** [comment]
If it worked fine or at least better it might be caused by the updated dependency in 0.7.4 

Need to look deeper into it

**Comment by bjoernQ** [comment]
I'll try to update Javassist to 3.27.0-GA which has been release 22 days ago - hope that will fix your problem

**Comment by bjoernQ** [comment]
Just pushed a new version (0.7.6) using Javassist 3.27.0-GA - hope it solves your issues
